name: CodeCov
on: [push, pull_request]
# on: 
#   # Replace with your main branch if needed
#   push:
#     branches:
#       - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: 'generate report'
      run: |
        pip install pytest
        pip install coverage
        pip install scikit-learn
        pip install numpy
        pip install pandas
        pip install imbalanced-learn
        pip install scipy
        pip install ipywidgets
        pip install IPython
        pip install matplotlib
        coverage run -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
